import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Navbar } from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="m-0 p-0 box-border">
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          "antialiased",
          "bg-black text-[#e7e7e7] min-h-screen leading-1.5",
        )}
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
